force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Postal_Code__c</fullName>
    <label>Billing Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <label>Billing State</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Billing Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <label>Client Code</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Client__c/fields/Client_Fax__c.field-meta.xml
<CustomField>
    <fullName>Client_Fax__c</fullName>
    <description>Data type Phone is used for New Fax field on Client Object.</description>
    <label>Fax</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Client_Group__c.field-meta.xml
<CustomField>
    <fullName>Client_Group__c</fullName>
    <label>Client Group</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biodisel</fullName>
            </value>
            <value>
                <fullName>AccuDate</fullName>
            </value>
            <value>
                <fullName>Advantage</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>All Shops</fullName>
            </value>
            <value>
                <fullName>All Stores</fullName>
            </value>
            <value>
                <fullName>Arby&apos;s</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>B18</fullName>
            </value>
            <value>
                <fullName>B5</fullName>
            </value>
            <value>
                <fullName>Baskets</fullName>
            </value>
            <value>
                <fullName>BBQ</fullName>
            </value>
            <value>
                <fullName>BTC</fullName>
            </value>
            <value>
                <fullName>Bump Bar</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Carls&apos; Jr.</fullName>
            </value>
            <value>
                <fullName>Chester&apos;s</fullName>
            </value>
            <value>
                <fullName>CMN Footballs</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Country Stores</fullName>
            </value>
            <value>
                <fullName>CS/TS/Speedco</fullName>
            </value>
            <value>
                <fullName>Curtis</fullName>
            </value>
            <value>
                <fullName>Deposit Bag Dual</fullName>
            </value>
            <value>
                <fullName>Deposit Bag Single</fullName>
            </value>
            <value>
                <fullName>District 1901</fullName>
            </value>
            <value>
                <fullName>District 1902</fullName>
            </value>
            <value>
                <fullName>District 1903</fullName>
            </value>
            <value>
                <fullName>District 1904</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client__c/fields/Fax__c.field-meta.xml
<CustomField>
    <fullName>Fax__c</fullName>
    <label>Old Fax</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Contact__c/Client_Contact__c.object-meta.xml
<CustomObject>
    <label>Client Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Contact__c/fields/Business_Phone__c.field-meta.xml
<CustomField>
    <fullName>Business_Phone__c</fullName>
    <label>Business Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Client_Contact__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Contact__c/fields/Client_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact_Role__c</fullName>
    <label>Client Contact Role</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Contact__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <description>UserName</description>
    <label>UserName</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Spec__c/Job_Spec__c.object-meta.xml
<CustomObject>
    <label>Creative Brief</label>
    <nameField>
        <label>Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Briefs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Media_Type__c/fields/Dummy_Picklist_1__c.field-meta.xml
<CustomField>
    <fullName>Dummy_Picklist_1__c</fullName>
    <label>Dummy Picklist 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dummy 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CMNFormOrdersController.cls
public with sharing class CMNFormOrdersController 
{
    
     public boolean isTab{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4t' || theme=='Theme4d')?true:false;
                                          }
    }
    
    
    
    Public boolean ShowCMNForm{get;set;}  //  added new form CMN Form in Store Order type
    Public boolean ShowCMNBannerForm{get;set;} 
    Public boolean ShowCMNConForm{get;set;} 
    Public Schedule_Template__c CMNScheduletype{get;set;}
    Public Media_Type__c NameMediatype{get;set;}
    Public Client_Contact__c  clientContact{get;set;}
    Public User lstUser{get;set;} 
   
    Public String CMNFlyerNameofEvent{get;set;}
    Public String CMNFlyerDate{get;set;}
    Public String CMNFlyerTime{get;set;}
    Public String CMNFlyerEventDetails{get;set;}
    Public String CMNFlyerSpecialDetails{get;set;}
    
    Public String CMNBannerNameofEvent{get;set;}
    Public String CMNBannerDate{get;set;}
    Public String CMNBannerTime{get;set;}
    Public String CMNBannerEventDetails{get;set;}
    Public String CMNBannerSpecialDetails{get;set;}
    Public Boolean FlyerApproved{get;set;}
    Public Boolean BannerApproved{get;set;}
    
    
    
    public CMNFormOrdersController()
    {
        ShowCMNForm=true;
        ShowCMNBannerForm=false;
        ShowCMNConForm=false;
        
            NameMediatype=[Select id ,name from Media_Type__c where name='Print' limit 1];
            CMNScheduletype=[Select id , name,Media_Types__c from Schedule_Template__c where name ='CMN' AND Media_Types__r.name='Print' limit 1];//  added new form CMN Form in Store Order type
            lstUser = [select firstname ,Username,Id, Profile.Name  from user where id=:userinfo.getuserid() ];
            clientcontact=[Select id,Mobile_Phone__c,Client_Contact_Role__c,Business_Phone__c,Fax__c,Email__c , name,Client__c,UserName__c,Client__r.Client_Code__c,Client__r.Dummy_Picklist_1__c, Client__r.Client_Group__c,Client__r.Name ,Client__r.Billing_City__c , Client__r.Billing_Postal_Code__c,Client__r.Billing_Street__c , Client__r.Billing_State__c,Client__r.Client_Fax__c , Client__r.Phone__c   from Client_Contact__c where UserName__c =:lstUser.Username];
            System.debug('ClientContact'+clientcontact.name);
    }
    
    public void CMNBMethod() 
    {
      
         if((string.isBlank(CMNFlyerNameofEvent)) || (string.isBlank(CMNFlyerDate)) || (string.isBlank(CMNFlyerTime)))
         {
             if(string.isBlank(CMNFlyerNameofEvent))
             {
                 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please Enter the Name of Event'));
             }
             if(string.isBlank(CMNFlyerDate))
             {
                  ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please Enter the Date'));
             }
             if(string.isBlank(CMNFlyerTime))
             {
                  ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please Enter the Time'));
             }
             
         }
         else
         {
            ShowCMNForm=false;
            ShowCMNBannerForm=true;
            ShowCMNConForm=false;
         }
          
       
          
    }


    public PageReference Back() 
    {
        PageReference pageRef = new PageReference('/apex/StorefrontJobRequestForm');
        pageRef.setRedirect(true);
        return pageRef;
    }
    
    public void CMNConMethod() 
    {    
    
         if((string.isBlank(CMNBannerNameofEvent)) || (string.isBlank(CMNBannerTime)) || (string.isBlank(CMNBannerDate)))
         {
             if(string.isBlank(CMNBannerNameofEvent))
             {
                 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please Enter the Name of Event'));
             }
             if(string.isBlank(CMNBannerTime))
             {
                  ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please Enter the Time'));
             }
             if(string.isBlank(CMNBannerDate))
             {
                  ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please Enter the Date'));
             }
             
         }
         else
         {
        
            ShowCMNConForm=true;
            ShowCMNForm=false;
            ShowCMNBannerForm=false;
         }
         
          
    }


    public void BackToFlyer() 
    {
        ShowCMNForm=true;
        ShowCMNBannerForm=false;
        ShowCMNConForm=false;
    }
    
    
    public PageReference order() 
    {
    
    
         if(FlyerApproved==false||BannerApproved==false)
         {
             if(FlyerApproved==false)
             {
                 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please approve the CMN Flyer Template'));
             }
             if(BannerApproved==false)
             {
                  ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please approve the CMN Banner Template'));
             }
        }
    
       try
       {
            Job__c CMNJob=new Job__c();
                CMNJob.Media_Types__c=NameMediatype.id;
                CMNJob.Schedule_Template__c=CMNScheduletype.id;
                CMNJob.JS_Client__c=clientcontact.Client__c;
                CMNJob.JS_Client_Contact__c=clientcontact.id;
                CMNJob.JobFormTypeValues__c='CMN Form';
            insert CMNJob; 
            
            Job_Spec__c CMNSpecFlyerName=new Job_Spec__c();
                CMNSpecFlyerName.Name='Name of Event';
                CMNSpecFlyerName.Description__c=CMNFlyerNameofEvent;
                CMNSpecFlyerName.Job__c=CMNJob.id;
                CMNSpecFlyerName.Creative_Brief_Template__c='Flyers';
            insert CMNSpecFlyerName;
                
                
            Job_Spec__c CMNSpecFlyerDate=new Job_Spec__c();
                CMNSpecFlyerDate.Name='Date';
                CMNSpecFlyerDate.Description__c=CMNFlyerDate;
                CMNSpecFlyerDate.Job__c=CMNJob.id;
                CMNSpecFlyerDate.Creative_Brief_Template__c='Flyers';
            insert CMNSpecFlyerDate;
                
            Job_Spec__c CMNSpecFlyerTime=new Job_Spec__c();
                CMNSpecFlyerTime.Name='Time';
                CMNSpecFlyerTime.Description__c=CMNFlyerTime;
                CMNSpecFlyerTime.Job__c=CMNJob.id;
                CMNSpecFlyerTime.Creative_Brief_Template__c='Flyers';
            insert CMNSpecFlyerTime;
                
            Job_Spec__c CMNSpecFlyerEvent=new Job_Spec__c();
                CMNSpecFlyerEvent.Name='Event Details';
                CMNSpecFlyerEvent.Description__c=CMNFlyerEventDetails;
                CMNSpecFlyerEvent.Job__c=CMNJob.id;
                CMNSpecFlyerEvent.Creative_Brief_Template__c='Flyers';
            insert CMNSpecFlyerEvent;
            
            
            Job_Spec__c CMNSpecFlyerSpecial=new Job_Spec__c();
                CMNSpecFlyerSpecial.Name='Special Details';
                CMNSpecFlyerSpecial.Description__c=CMNFlyerSpecialDetails;
                CMNSpecFlyerSpecial.Job__c=CMNJob.id;
                CMNSpecFlyerSpecial.Creative_Brief_Template__c='Flyers';
            insert CMNSpecFlyerSpecial;
            
           
           Job_Spec__c CMNSpecBannerName=new Job_Spec__c();
                CMNSpecBannerName.Name='Name of Event';
                CMNSpecBannerName.Description__c=CMNBannerNameofEvent;
                CMNSpecBannerName.Job__c=CMNJob.id;
                CMNSpecBannerName.Creative_Brief_Template__c='Banner';
            insert CMNSpecBannerName;
                
                
            Job_Spec__c CMNSpecBannerDate=new Job_Spec__c();
                CMNSpecBannerDate.Name='Date';
                CMNSpecBannerDate.Description__c=CMNBannerDate;
                CMNSpecBannerDate.Job__c=CMNJob.id;
                CMNSpecBannerDate.Creative_Brief_Template__c='Banner';
            insert CMNSpecBannerDate;
                
            Job_Spec__c CMNSpecBannerTime=new Job_Spec__c();
                CMNSpecBannerTime.Name='Time';
                CMNSpecBannerTime.Description__c=CMNBannerTime;
                CMNSpecBannerTime.Job__c=CMNJob.id;
                CMNSpecBannerTime.Creative_Brief_Template__c='Banner';
            insert CMNSpecBannerTime;
                
            Job_Spec__c CMNSpecBannerEvent=new Job_Spec__c();
                CMNSpecBannerEvent.Name='Event Details';
                CMNSpecBannerEvent.Description__c=CMNBannerEventDetails;
                CMNSpecBannerEvent.Job__c=CMNJob.id;
                CMNSpecBannerEvent.Creative_Brief_Template__c='Banner';
            insert CMNSpecBannerEvent;
            
            
            Job_Spec__c CMNSpecBannerSpecial=new Job_Spec__c();
                CMNSpecBannerSpecial.Name='Special Details';
                CMNSpecBannerSpecial.Description__c=CMNBannerSpecialDetails;
                CMNSpecBannerSpecial.Job__c=CMNJob.id;
                CMNSpecBannerSpecial.Creative_Brief_Template__c='Banner';
            insert CMNSpecBannerSpecial;
            
        if(isTab)
        {
            PageReference pageRef = new PageReference('/apex/DisplayJobsforClientContactLightning');
            pageRef.setRedirect(true);
            return pageRef;
        }
           
           PageReference pageRef = new PageReference('/apex/DisplayJobsforClientContact');
           pageRef.setRedirect(true);
           return pageRef;
        
         /*   PageReference pageRef = new PageReference('/apex/DisplayJobsforClientContact');
            pageRef.setRedirect(true);
            return pageRef;*/
            
        }
        
         catch(Exception e)
         {
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,e.getmessage()));
             return null;
         }
     
           return null;
        
    }
   

    



}