force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Client_Group__c.field-meta.xml
<CustomField>
    <fullName>Client_Group__c</fullName>
    <label>Client Group</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Biodisel</fullName>
            </value>
            <value>
                <fullName>AccuDate</fullName>
            </value>
            <value>
                <fullName>Advantage</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>All Shops</fullName>
            </value>
            <value>
                <fullName>All Stores</fullName>
            </value>
            <value>
                <fullName>Arby&apos;s</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>B18</fullName>
            </value>
            <value>
                <fullName>B5</fullName>
            </value>
            <value>
                <fullName>Baskets</fullName>
            </value>
            <value>
                <fullName>BBQ</fullName>
            </value>
            <value>
                <fullName>BTC</fullName>
            </value>
            <value>
                <fullName>Bump Bar</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Carls&apos; Jr.</fullName>
            </value>
            <value>
                <fullName>Chester&apos;s</fullName>
            </value>
            <value>
                <fullName>CMN Footballs</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Country Stores</fullName>
            </value>
            <value>
                <fullName>CS/TS/Speedco</fullName>
            </value>
            <value>
                <fullName>Curtis</fullName>
            </value>
            <value>
                <fullName>Deposit Bag Dual</fullName>
            </value>
            <value>
                <fullName>Deposit Bag Single</fullName>
            </value>
            <value>
                <fullName>District 1901</fullName>
            </value>
            <value>
                <fullName>District 1902</fullName>
            </value>
            <value>
                <fullName>District 1903</fullName>
            </value>
            <value>
                <fullName>District 1904</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Contact__c/Client_Contact__c.object-meta.xml
<CustomObject>
    <label>Client Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Contact__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Contact__c/fields/Salesforce_User__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Salesforce User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Contact__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <description>UserName</description>
    <label>UserName</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <label>Holiday</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Item__c/Material_Item__c.object-meta.xml
<CustomObject>
    <label>Material Item</label>
    <nameField>
        <label>Material Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Item__c/fields/Creative_Brief_Template__c.field-meta.xml
<CustomField>
    <fullName>Creative_Brief_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipLabel>Material Items</relationshipLabel>
    <relationshipName>Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Material_Item__c/fields/Production_Estimate_Template__c.field-meta.xml
<CustomField>
    <fullName>Production_Estimate_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Estimate Template</label>
    <referenceTo>Production_Estimate_Template__c</referenceTo>
    <relationshipLabel>Material Items</relationshipLabel>
    <relationshipName>Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Material_Item__c/fields/Store_Front__c.field-meta.xml
<CustomField>
    <fullName>Store_Front__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Store Front</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Material_Item__c/fields/Store_Type__c.field-meta.xml
<CustomField>
    <fullName>Store_Type__c</fullName>
    <label>Client Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BioDiesel</fullName>
            </value>
            <value>
                <fullName>AccuDate</fullName>
            </value>
            <value>
                <fullName>Advantage</fullName>
            </value>
            <value>
                <fullName>All Shops</fullName>
            </value>
            <value>
                <fullName>All Stores</fullName>
            </value>
            <value>
                <fullName>Arby&apos;s</fullName>
            </value>
            <value>
                <fullName>B18</fullName>
            </value>
            <value>
                <fullName>B5</fullName>
            </value>
            <value>
                <fullName>Baskets</fullName>
            </value>
            <value>
                <fullName>BBQ</fullName>
            </value>
            <value>
                <fullName>Beer Draft</fullName>
            </value>
            <value>
                <fullName>BTC</fullName>
            </value>
            <value>
                <fullName>Bump Bar</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Carl&apos;s Jr.</fullName>
            </value>
            <value>
                <fullName>Chester&apos;s</fullName>
            </value>
            <value>
                <fullName>CMN Footballs</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Country Stores</fullName>
            </value>
            <value>
                <fullName>CS/TS/Speedco</fullName>
            </value>
            <value>
                <fullName>Curtis</fullName>
            </value>
            <value>
                <fullName>DEF</fullName>
            </value>
            <value>
                <fullName>Deposit Bag Dual</fullName>
            </value>
            <value>
                <fullName>Deposit Bag Single</fullName>
            </value>
            <value>
                <fullName>DM Only</fullName>
            </value>
            <value>
                <fullName>Dog Park</fullName>
            </value>
            <value>
                <fullName>EBT</fullName>
            </value>
            <value>
                <fullName>Empanada</fullName>
            </value>
            <value>
                <fullName>EM Production</fullName>
            </value>
            <value>
                <fullName>Encore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Material_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Item Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Banners</fullName>
            </value>
            <value>
                <fullName>Forms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Media_Type__c/Media_Type__c.object-meta.xml
<CustomObject>
    <label>Media Type</label>
    <nameField>
        <label>Media Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Production_Estimate_Temp_Line_Items__c/Production_Estimate_Temp_Line_Items__c.object-meta.xml
<CustomObject>
    <label>Production Estimate Temp Line Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimate Temp Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Production_Estimate_Temp_Line_Items__c/fields/Material_Item__c.field-meta.xml
<CustomField>
    <fullName>Material_Item__c</fullName>
    <label>Material Item</label>
    <referenceTo>Material_Item__c</referenceTo>
    <relationshipLabel>Production Estimate Temp Line Items</relationshipLabel>
    <relationshipName>Production_Estimate_Temp_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Production_Estimate_Template__c/Production_Estimate_Template__c.object-meta.xml
<CustomObject>
    <label>Production Estimate Template</label>
    <nameField>
        <label>Production Estimate Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimate Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Spec_Item__c/Spec_Item__c.object-meta.xml
<CustomObject>
    <label>Creative Spec Items</label>
    <nameField>
        <label>Spec Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spec Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TrilliumJobRequestLtCtrlTest.cls
@isTest
public class TrilliumJobRequestLtCtrlTest {
    static testmethod void tesmethod(){
        Specification_Template__c testSpec1=new Specification_Template__c(Name='Testing Spcification Template 1310');
        insert testSpec1;
        
        Production_Estimate_Template__c testPEtemp=new Production_Estimate_Template__c(Name='Testing PE Temp');
        insert testPEtemp;
        
         
         
        Spec_Item__c testSPI1=new Spec_Item__c(Name='Test SPI 1310',Description__c='Test Desc 1310',Specification_Template__c=testSpec1.id);
        insert testSPI1;     
        
        
        Material_Item__c  Material=new Material_Item__c (name='test 123',Type__c='Trillium CNG',Store_Type__c ='test',Store_Front__c=true,Creative_Brief_Template__c=testSpec1.id,Production_Estimate_Template__c=testPEtemp.id);
        insert Material;
        
        Production_Estimate_Temp_Line_Items__c testPELine=new Production_Estimate_Temp_Line_Items__c(Name='PELine',Material_Item__c=Material.id,Production_Estimate_Template__c=testPEtemp.id);
        insert testPELine;
        
        Client__c testClient=new Client__c(Name='Trillium CNG',Client_Group__c='Test;ui');
        insert testClient;
        
        
        Client_Contact__c testclientcontact = new Client_Contact__c(Client__c=testClient.id,Active__c=true,Email__c='demo3@gmail.com',UserName__c='demo3@test1.com',First_Name__c='demo3',Last_Name__c='Testing3',Salesforce_User__c=true  );         
        insert  testclientcontact ;  
        
        user lstUser = [select firstname ,Username,Id, Profile.Name  from user where Username=:testclientcontact.UserName__c ];
        
        Client_Contact__c TestClientCon=[select id, name,UserName__c,Client__c, Client__r.Name   from Client_Contact__c  where UserName__c =:lstUser.Username];
        
        Media_Type__c MediaType= new Media_Type__c (name='Print');
        insert MediaType;
        
        Media_Type__c StoreMediaType= new Media_Type__c (name='Supplies');
        insert StoreMediaType;
        
        Media_Type__c BillboardMediatype= new Media_Type__c (name='Outdoor');
        insert BillboardMediatype;
        
        Schedule_Template__c NameTagScheduletype =new Schedule_Template__c ( name ='Name Tag',Media_Types__c = MediaType.id);
        insert NameTagScheduletype ;
        
        Schedule_Template__c NamePlateScheduletype =new Schedule_Template__c ( name ='Corporate Office Nameplate',Media_Types__c = MediaType.id);
        insert NamePlateScheduletype ;
        
        Schedule_Template__c NameStoreScheduletype=new Schedule_Template__c ( name ='Made To Order',Media_Types__c = MediaType.id);
        insert NameStoreScheduletype;  
        
        Schedule_Template__c NameBusinessCardScheduletype=new Schedule_Template__c ( name ='Store Business Card',Media_Types__c = MediaType.id);
        insert NameBusinessCardScheduletype;  
        
        Schedule_Template__c NameCorporateCardScheduletype=new Schedule_Template__c ( name ='Corporate Business Card',Media_Types__c = MediaType.id);
        insert NameCorporateCardScheduletype;
        
        Schedule_Template__c NameBillboardScheduletype=new Schedule_Template__c ( name ='Billboard Repair',Media_Types__c = BillboardMediatype.id);
        insert NameBillboardScheduletype;
        
        Holiday__c holiday=new Holiday__c(Date__c=System.today());
        insert holiday;
        
       // System.runAs(lstUser) 
        //{
            TrilliumJobRequestLtCtrl.getClientContacts();
            TrilliumJobRequestLtCtrl.getMaterialItemList();
            TrilliumJobRequestLtCtrl.showItems('test');
            TrilliumJobRequestLtCtrl.MaterialItemWrapper miWrpr=new TrilliumJobRequestLtCtrl.MaterialItemWrapper();
            miWrpr.MIWrap=Material;
            miWrpr.MISelect=true;
            TrilliumJobRequestLtCtrl.getCombinedList(new list<Client_Contact__c>{testclientcontact}, new list<TrilliumJobRequestLtCtrl.MaterialItemWrapper>{miWrpr});
            TrilliumJobRequestLtCtrl.CombinedWrapper cmbWrpr=new TrilliumJobRequestLtCtrl.CombinedWrapper();
            TrilliumJobRequestLtCtrl.CombinedWrapperItem cmbItem=new TrilliumJobRequestLtCtrl.CombinedWrapperItem();
            cmbItem.mItem=Material;
            cmbItem.enteredQty=2;
            cmbWrpr.Email='test@test.com';
            cmbWrpr.BillingInstru='test';
            cmbWrpr.itemsList=new list< TrilliumJobRequestLtCtrl.CombinedWrapperItem>{cmbItem};
            TrilliumJobRequestLtCtrl.placeOrder(new list<TrilliumJobRequestLtCtrl.CombinedWrapper>{cmbWrpr},new list<Material_Item__c>{Material});
            cmbWrpr.editmode=true;
            TrilliumJobRequestLtCtrl.placeOrder(new list<TrilliumJobRequestLtCtrl.CombinedWrapper>{cmbWrpr},new list<Material_Item__c>{Material});
            cmbWrpr.Acceptance=true;
            TrilliumJobRequestLtCtrl.placeOrder(new list<TrilliumJobRequestLtCtrl.CombinedWrapper>{cmbWrpr},new list<Material_Item__c>{Material});
       	
       // }
    } 
}