force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Contact__c/Client_Contact__c.object-meta.xml
<CustomObject>
    <label>Client Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Contact__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/lwc_customLookUpController.cls
public with sharing class lwc_customLookUpController {
    
    @AuraEnabled(cacheable=true)
    public static List<sObject> search(String searchTerm,string objname,string mediaid) {
        system.debug('search term === '+searchTerm);
        system.debug('objectapiname === '+objname);
        system.debug('mediaid === '+mediaid);
        List <sObject> returnList = new List <SObject> ();
        if(string.isNotEmpty(searchTerm)){
            DescribeSObjectResult describeResult =Schema.getGlobalDescribe().get(objname).getDescribe();
            string searchword = searchTerm + '%';
            String sQuery =' SELECT Id,Name FROM ' + describeResult.getName() +' where Name LIKE: searchword ';
            returnList = Database.query(sQuery);
            System.debug('======SOquey of Media Type========'+sQuery);
        }
        return returnList;
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<Schedule_Template__c> getschtemprcd(string searchTerm,string mediaid) {
        string searchword = searchTerm + '%';
        list<Schedule_Template__c>schrcd = [select id,name,Media_Types__c from Schedule_Template__c where name like:searchword and Media_Types__c =: mediaid];
        return schrcd;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Client_Contact__c> getclientcntrcd(string searchTerm,string clientid) {
        string searchword = searchTerm + '%';
        list<Client_Contact__c>clientcntrcd = [select id,name,Client__c from Client_Contact__c  where name like:searchword and Client__c =: clientid];
        return clientcntrcd;
    }
    
    /* old blog method 
@AuraEnabled(cacheable=true)
public static List<sObject> search(String searchTerm, string myObject, String filter) {
system.debug('search term === '+searchTerm);
system.debug('myObject === '+myObject);
system.debug('filter === '+filter);

String myQuery = null;
if(filter != null && filter != ''){
myQuery = 'Select Id, Name from '+myObject+' Where Name Like  \'%' + searchTerm + '%\' AND '+filter+' LIMIT  5';
}
else {
if(searchTerm == null || searchTerm == ''){
}
else {
myQuery = 'Select Id, Name from '+myObject+' Where Name Like  \'%' + searchTerm + '%\' LIMIT  5';
}
}
List<sObject> lookUpList = database.query(myQuery);
return lookUpList;
}*/
}