force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Spec__c/Job_Spec__c.object-meta.xml
<CustomObject>
    <label>Creative Brief</label>
    <nameField>
        <label>Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Briefs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Task__c/Job_Task__c.object-meta.xml
<CustomObject>
    <label>Job Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Team__c/Job_Team__c.object-meta.xml
<CustomObject>
    <label>Job Team</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>JobTeam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Team__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Team</relationshipLabel>
    <relationshipName>Job_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Team__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Team__c/fields/Staff__c.field-meta.xml
<CustomField>
    <fullName>Staff__c</fullName>
    <label>Staff</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Material_Item__c/Material_Item__c.object-meta.xml
<CustomObject>
    <label>Material Item</label>
    <nameField>
        <label>Material Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Item__c/fields/Calc_Unit__c.field-meta.xml
<CustomField>
    <fullName>Calc_Unit__c</fullName>
    <label>Calc Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Size</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Material_Item__c/fields/Creative_Brief_Template__c.field-meta.xml
<CustomField>
    <fullName>Creative_Brief_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creative Brief Template</label>
    <referenceTo>Specification_Template__c</referenceTo>
    <relationshipLabel>Material Items</relationshipLabel>
    <relationshipName>Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Production_Estimate__c/Production_Estimate__c.object-meta.xml
<CustomObject>
    <label>Production Estimate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Production_Estimate__c/fields/Calc_Unit__c.field-meta.xml
<CustomField>
    <fullName>Calc_Unit__c</fullName>
    <label>Calc Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Size</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Production_Estimate__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job Name</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Production_Estimate__c/fields/Length_in_Inches__c.field-meta.xml
<CustomField>
    <fullName>Length_in_Inches__c</fullName>
    <label>Length in Inches</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Production_Estimate__c/fields/Material_Item__c.field-meta.xml
<CustomField>
    <fullName>Material_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Item</label>
    <referenceTo>Material_Item__c</referenceTo>
    <relationshipLabel>Production Estimates</relationshipLabel>
    <relationshipName>Production_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Production_Estimate__c/fields/PE_Template__c.field-meta.xml
<CustomField>
    <fullName>PE_Template__c</fullName>
    <label>PE Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Production_Estimate__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Qty</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Production_Estimate__c/fields/Width_in_Inches__c.field-meta.xml
<CustomField>
    <fullName>Width_in_Inches__c</fullName>
    <label>Width in Inches</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>Ship-{000000}</displayFormat>
        <label>Shipment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/WorkOrderNewExtension.cls
public with sharing class WorkOrderNewExtension {

   // Global variables  
    public DateTime today{get;set;}
    String jobid;
    public List<Job_Team__c> JobTeam{get;set;} 
    public List<Job_Task__c> JobTask{get;set;} 
    public List<Job_Spec__c> CreativeBrief{get;set;}
    Public List<Production_Estimate__c> ProdEstMaterialitems{get;set;}
    public List<Shipment__c> Shipment{get;set;}
    
    public String imageBody{get;set;}
    public String imageURL{get;set;}
    public List<Document> lstDoc;
    public boolean imageNotFound{get;set;}
    public map<string,list<Job_Spec__c>> MapCB{get;set;}
    public map<string,list<Production_Estimate__c>> MapPE{get;set;}
  
    // End Global variables

      // Start Constructor
    public WorkOrderNewExtension (ApexPages.StandardController controller) 
    {
         // To display Subscriber Organization Logo
         imageURL = '/servlet/servlet.FileDownload?file='; 
        lstDoc = [Select Id, Name, Body from Document where Name =: 'JobSuite_OrganizationLogo' LIMIT 1];
        if(!lstDoc.isEmpty())
        {
           String imageId =  lstDoc[0].Id;
           imageBody = imageURL+imageId; 
           imageNotFound = False;
        }    
        else
        {
           imageNotFound = True;
        }
            
       jobid = ApexPages.currentpage().getParameters().get('id');
       JobTeam = [select id,Name,Role__c,Staff__c from Job_Team__c where Job__c =: jobid];
       CreativeBrief = [select id,Name,Description__c,Creative_Brief_Template__c from Job_Spec__c where Job__c =: jobid order By Sort_Order__c];
       JobTask = [select id,Name,Due_Date__c,Start_Date__c,Revised_Due_Date__c,Task_Order__c,Marked_Done__c,Assigned_Users__c from Job_Task__c where Job__c =: jobid Order By Task_Order__c];
       ProdEstMaterialitems=[select id,name,PE_Template__c,Material_Item__c ,Material_Item__r.Calc_Unit__c, Quantity__c,Length_in_Inches__c,Width_in_Inches__c,Material_Item__r.name  from Production_Estimate__c where Job__c =: jobid order By Sort_Order__c];
       Shipment=[select id,name,Shipment_Phone__c,TO_ATTN__c,Shipment_Street_Address__c,Shipment_Address_2__c,Shipment_City__c,Shipment_State__c,Shipment_Zip_code__c from Shipment__c where Job__c =: jobid];
       
       
         MapCB = new map<string,list<Job_Spec__c>>();
         
         for(Job_Spec__c JS:CreativeBrief)
         {
               if(MapCB.containsKey(js.Creative_Brief_Template__c))
               {
                  List <Job_Spec__c > jSpeclist =  MapCB.get(js.Creative_Brief_Template__c);
                  jSpeclist.add(js);
                  MapCB.put(js.Creative_Brief_Template__c,jSpeclist );  
                }
                else
                {
                  MapCB.put(js.Creative_Brief_Template__c, new List<Job_Spec__c >{js}) ;
                }   
         
         }
         
         
          MapPE = new map<string,list<Production_Estimate__c>>();
         
         for(Production_Estimate__c JS:ProdEstMaterialitems)
         {
               if(MapPE.containsKey(js.PE_Template__c))
               {
                  List <Production_Estimate__c> PElist =  MapPE .get(js.PE_Template__c);
                  PElist.add(js);
                  MapPE.put(js.PE_Template__c,PElist);  
                }
                else
                {
                  MapPE.put(js.PE_Template__c, new List<Production_Estimate__c>{js}) ;
                }   
         
         }
       
       
       
       
       today=System.NOW();
    }
    // End Constructor 
    /*
         <tr><td style="width:50%">
          <apex:image value="{!$Resource.WorkorderQClogo}"/>
        </td>
        </tr>*/

}