force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <description>This is Campaign object.</description>
    <label>JS Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JS Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Postal_Code__c</fullName>
    <label>Billing Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <label>Billing State</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Billing Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Client_Fax__c.field-meta.xml
<CustomField>
    <fullName>Client_Fax__c</fullName>
    <description>Data type Phone is used for New Fax field on Client Object.</description>
    <label>Fax</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hierarchy</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Contact__c/Client_Contact__c.object-meta.xml
<CustomObject>
    <label>Client Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Contact__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Contact__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <description>UserName</description>
    <label>UserName</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_Template__c/Schedule_Template__c.object-meta.xml
<CustomObject>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification_Template__c/Specification_Template__c.object-meta.xml
<CustomObject>
    <label>Creative Brief Template</label>
    <nameField>
        <label>Creative Brief Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creative Brief Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DisplayJobsforClientContact.cls
public with sharing class DisplayJobsforClientContact {

  Public List<Job__c> JobList {get;set;}
  Public Client_Contact__c  clientContact{get;set;}
  Public User lstUser{get;set;}
  public String strStatus{get;set;}
  Public string clientname{get;set;}
    integer count;
    integer countstr;
    public List<selectOption> getStatusList() 
    {
        List<selectOption> optionList = new List<selectOption>();
        Schema.DescribeFieldResult field = Job__c.Status__c.getDescribe();
         optionList.add(new selectOption('All Jobs', 'All Jobs')); 
        for (Schema.PicklistEntry a : field.getPicklistValues()) 
        {  
            optionList.add(new selectOption(a.getLabel(), a.getLabel()));  
        }
        
        return optionList;  
    }
    // End of Global variables
  
   
     public  DisplayJobsforClientContact(){
      strStatus= 'Active';
      lstUser = [select firstname ,Username,Id, Profile.Name  from user where id=:userinfo.getuserid()];
      clientcontact=[Select id,Email__c , name,Client__c,UserName__c, Client__r.Name ,Client__r.Billing_City__c , Client__r.Billing_Postal_Code__c,Client__r.Billing_Street__c , Client__r.Billing_State__c,Client__r.Client_Fax__c , Client__r.Phone__c   from Client_Contact__c where UserName__c =:lstUser.Username];
      
      clientname=clientcontact.Client__r.Name;
      
      system.debug('***clientname***'+clientname);
      
      if(clientname.contains('Store')){
      
            JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where   JS_Client__c  =:clientcontact.Client__c and Status__c = :'Active' And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      
      }
      
      
      if(clientname.contains('District')){
      
            JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where (JS_Client__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__c  =:clientcontact.Client__c) and Status__c = :'Active' And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      
      }
      
      
      
      if(clientname.contains('Division')){
      
            JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where (JS_Client__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__r.Hierarchy__c  =:clientcontact.Client__c) and Status__c = :'Active' And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      }
      
      else{
         JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where   JS_Client__c  =:clientcontact.Client__c and Status__c = :'Active' And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      }
      
     system.debug('***JobList Constructor***'+JobList);
     
     
      system.debug('***Client***'+clientcontact.Client__r.Name);
      system.debug('***Client Contact***'+clientcontact.name);
    
      
       }
       
       
    public void populateJobList()
      {
     
         count = [select count() from Job__c where JS_Client__c =:clientcontact.Client__c];
         if(strStatus != 'All Jobs')
         {
          countstr = [select count() from Job__c  where JS_Client__c =:clientcontact.Client__c ];
          }
          else
          {
            countstr = [select count() from Job__c where JS_Client__c =:clientcontact.Client__c and Status__c = :strStatus ];
          }
        
       
          if(strStatus == 'All Jobs')
          {
          
              if(count>1000)
              {
              
              if(clientname.contains('Store')){
      
                  JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where   JS_Client__c  =:clientcontact.Client__c And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      
                 }
      
      
               if(clientname.contains('District')){
      
                   JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where (JS_Client__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__c  =:clientcontact.Client__c) And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      
                }
      
      
      
             if(clientname.contains('Division')){
      
                JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where (JS_Client__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__r.Hierarchy__c  =:clientcontact.Client__c) And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

             }
             
             else{
         JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where   JS_Client__c  =:clientcontact.Client__c and CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      }
             
             
         }else
              {
              
              
              if(clientname.contains('Store')){
      
                  JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where   JS_Client__c  =:clientcontact.Client__c And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      
                 }
      
      
               if(clientname.contains('District')){
      
                   JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where (JS_Client__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__c  =:clientcontact.Client__c) And  CreatedBy.Profile.Name ='SP Client Contact'  ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      
                }
      
      
      
             if(clientname.contains('Division')){
      
                JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where (JS_Client__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__r.Hierarchy__c  =:clientcontact.Client__c) And  CreatedBy.Profile.Name ='SP Client Contact'  ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

             }
             else{
         JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where   JS_Client__c  =:clientcontact.Client__c and CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      }
             
             
              }
          }
          else
          {
              if(countstr >1000 )
              {
              
               if(clientname.contains('Store')){
      
                  JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where   JS_Client__c  =:clientcontact.Client__c and Status__c = :strStatus And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      
                 }
      
      
               if(clientname.contains('District')){
      
                   JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where (JS_Client__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__c  =:clientcontact.Client__c) and Status__c = :strStatus And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      
                }
      
      
      
             if(clientname.contains('Division')){
      
                JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where (JS_Client__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__r.Hierarchy__c  =:clientcontact.Client__c) and Status__c = :strStatus And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

             }
              
           else{
         JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where   JS_Client__c  =:clientcontact.Client__c and Status__c = :strStatus And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      }   
              
             
             
             
              }else
              {
                
                
                if(clientname.contains('Store')){
      
                  JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where   JS_Client__c  =:clientcontact.Client__c and Status__c = :strStatus And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      
                 }
      
      
               if(clientname.contains('District')){
      
                   JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where (JS_Client__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__c  =:clientcontact.Client__c) and Status__c = :strStatus And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      
                }
      
      
      
             if(clientname.contains('Division')){
      
                JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where (JS_Client__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__c  =:clientcontact.Client__c OR JS_Client__r.Hierarchy__r.Hierarchy__c  =:clientcontact.Client__c)  and Status__c = :strStatus And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

             }
             
             else{
         JobList=[Select id ,name ,JS_Client_Contact__c,JS_Client_Contact__r.name,JS_Client__r.name,JS_Client__c,Campaign__c,Specification_Template__c,Media_Types__c,Schedule_Template__c from Job__c where   JS_Client__c  =:clientcontact.Client__c and Status__c = :strStatus  And  CreatedBy.Profile.Name ='SP Client Contact' ORDER BY JOB_Auto_NUmber__c DESC LIMIT 1000];

      }
             
             
              }
          }
      
    }   
        
        
        
        


}