force-app/main/default/objects/Sample_Object_1__c/Sample_Object_1__c.object-meta.xml
<CustomObject>
    <label>Sample Object 1</label>
    <nameField>
        <label>Sample Object 1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sample Object 1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Object_1__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Securitycheckclass.cls
public class Securitycheckclass {
    
    public static void method1(){
        List<Sample_Object_1__c> sobj1 = [SELECT Id,name,Cost__c FROM Sample_Object_1__c WITH SECURITY_ENFORCED];
        system.debug('sobj1 === '+sobj1.size()); 
    }
    
    /*public static void method2() {
    List<Sample_Object_1__c> sobj1 = [SELECT Id, Name, Cost__c FROM Sample_Object_1__c];
    System.debug('sobj1 === ' + sobj1.size());
    SObjectAccessDecision sad = Security.stripInaccessible(
        Security.AccessType.READABLE, 
        sobj1
    );
    for (Sample_Object_1__c sobrcd : (List<Sample_Object_1__c>)sad.getRecords()) {
        System.debug('Safe Name: ' + sobrcd.Name); 
        System.debug('Safe Cost: ' + sobrcd.Cost__c); // may be null if not accessible
    }
}*/

}