force-app/main/default/objects/Material_Item__c/Material_Item__c.object-meta.xml
<CustomObject>
    <label>Material Item</label>
    <nameField>
        <label>Material Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Item__c/fields/Calc_Unit__c.field-meta.xml
<CustomField>
    <fullName>Calc_Unit__c</fullName>
    <label>Calc Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Size</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Material_Item__c/fields/Case_Pack__c.field-meta.xml
<CustomField>
    <fullName>Case_Pack__c</fullName>
    <label>Case Pack</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Material_Item__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qty On Hand</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Material_Item__c/fields/Rack__c.field-meta.xml
<CustomField>
    <fullName>Rack__c</fullName>
    <label>Rack</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
            </value>
            <value>
                <fullName>002</fullName>
            </value>
            <value>
                <fullName>003</fullName>
            </value>
            <value>
                <fullName>004</fullName>
            </value>
            <value>
                <fullName>005</fullName>
            </value>
            <value>
                <fullName>006</fullName>
            </value>
            <value>
                <fullName>007</fullName>
            </value>
            <value>
                <fullName>008</fullName>
            </value>
            <value>
                <fullName>009</fullName>
            </value>
            <value>
                <fullName>010</fullName>
            </value>
            <value>
                <fullName>011</fullName>
            </value>
            <value>
                <fullName>012</fullName>
            </value>
            <value>
                <fullName>013</fullName>
            </value>
            <value>
                <fullName>014</fullName>
            </value>
            <value>
                <fullName>015</fullName>
            </value>
            <value>
                <fullName>016</fullName>
            </value>
            <value>
                <fullName>017</fullName>
            </value>
            <value>
                <fullName>018</fullName>
            </value>
            <value>
                <fullName>019</fullName>
            </value>
            <value>
                <fullName>020</fullName>
            </value>
            <value>
                <fullName>021</fullName>
            </value>
            <value>
                <fullName>022</fullName>
            </value>
            <value>
                <fullName>023</fullName>
            </value>
            <value>
                <fullName>024</fullName>
            </value>
            <value>
                <fullName>025</fullName>
            </value>
            <value>
                <fullName>026</fullName>
            </value>
            <value>
                <fullName>027</fullName>
            </value>
            <value>
                <fullName>028</fullName>
            </value>
            <value>
                <fullName>029</fullName>
            </value>
            <value>
                <fullName>030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Material_Item__c/fields/Shelf__c.field-meta.xml
<CustomField>
    <fullName>Shelf__c</fullName>
    <label>Shelf</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>J</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>O</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>Q</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>T</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>W</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>Z</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Material_Item__c/fields/Shipping_Location__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Location__c</fullName>
    <label>Shipping Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2208</fullName>
            </value>
            <value>
                <fullName>312</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Material_Order__c/Material_Order__c.object-meta.xml
<CustomObject>
    <label>Material Purchase Order</label>
    <nameField>
        <displayFormat>MPO - {00000}</displayFormat>
        <label>Material Purchase Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Material_Order_Line_Item_Receipt__c/Material_Order_Line_Item_Receipt__c.object-meta.xml
<CustomObject>
    <label>Material Order Line Item Receipt</label>
    <nameField>
        <displayFormat>MOLI Receipt-{000000}</displayFormat>
        <label>Material Order Line Item Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Order Line Item Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Order_Line_Item_Receipt__c/fields/MPLI_Receipt_Status__c.field-meta.xml
<CustomField>
    <fullName>MPLI_Receipt_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outstanding</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Material_Purchase_Line_Item__c/Material_Purchase_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Material Order Line Item</label>
    <nameField>
        <displayFormat>MOLI-{000000}</displayFormat>
        <label>Material Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Purchase_Line_Item__c/fields/Material_Item__c.field-meta.xml
<CustomField>
    <fullName>Material_Item__c</fullName>
    <label>Material Item</label>
    <referenceTo>Material_Item__c</referenceTo>
    <relationshipName>Material_Purchase_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Material_Purchase_Line_Item__c/fields/Material_Order__c.field-meta.xml
<CustomField>
    <fullName>Material_Order__c</fullName>
    <label>Material Purchase Order</label>
    <referenceTo>Material_Order__c</referenceTo>
    <relationshipLabel>Material Order Line Items</relationshipLabel>
    <relationshipName>Material_Purchase_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Material_Purchase_Line_Item__c/fields/MPLI_Status__c.field-meta.xml
<CustomField>
    <fullName>MPLI_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outstanding</fullName>
                <default>true</default>
                <label>Outstanding</label>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Material_Purchase_Line_Item__c/fields/Qty_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Qty_Outstanding__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qty Outstanding</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Print_MO_Custom_Apexclass.cls
public class Print_MO_Custom_Apexclass {
    
    public String imageBody{get;set;}
    public String imageURL{get;set;}
    public boolean imageNotFound{get;set;}
    public List<Document> lstDoc;
    Public Boolean ShowProductionEstimate{get;set;}
    public list<Material_Purchase_Line_Item__c> molircds{get;set;}
    public list<Material_Order_Line_Item_Receipt__c>moliReceiptrcds{get;set;}
    public string Barcodeimageurl {get;set;}
    String MOid;
    
    
    public Print_MO_Custom_Apexclass(ApexPages.StandardController controller){
        ProductionEstimate__c  activeSettings = ProductionEstimate__c.getOrgDefaults();
        ShowProductionEstimate =activeSettings.Active__c;
        
        // Code to display Subsriber Organization Logo
        
        // If subscriber deletes the Document : JobSuite_OrganizationLogo from their Org then JobSuite App logo will be displayed
        
        imageURL = '/servlet/servlet.FileDownload?file='; 
        lstDoc = [Select Id, Name, Body from Document where Name =: 'JobSuite_OrganizationLogo' WITH SECURITY_ENFORCED LIMIT 1];
        if(!lstDoc.isEmpty())
        {
            String imageId =  lstDoc[0].Id;
            imageBody = imageURL+imageId; 
            imageNotFound = False;
        }    
        else
        {
            imageNotFound = True;
        }
        
        MOid = ApexPages.currentpage().getParameters().get('id');
        
        Material_Order__c morcd = [select id,Name,Status__c from Material_Order__c where id =: MOid  limit 1];
        
        molircds =   [select id,name,Material_Item__c, Material_Item__r.Shipping_Location__c,Material_Item__r.name,Material_Item__r.Qty_On_Hand__c,Material_Item__r.Case_Pack__c,Material_Item__r.Roll_LF__c,Material_Item__r.Rack__c,Material_Item__r.Shelf__c,Material_Order__c, Material_Order__r.name,MPLI_Status__c, Calc_Unit__c,Qty__c,Qty_Outstanding__c from Material_Purchase_Line_Item__c where Material_Order__c =: MOid WITH SECURITY_ENFORCED Order By CreatedDate desc];
        
        moliReceiptrcds =[select id,name,Material_Purchase_Line_Item__r.Material_Item__r.Name,Material_Purchase_Line_Item__r.Material_Item__c,Material_Purchase_Line_Item__c,Material_Purchase_Line_Item__r.name,MOLI_Receipt_Date__c,MOLI_Receipt_Qty__c,MPLI_Receipt_Status__c from Material_Order_Line_Item_Receipt__c where Material_Purchase_Line_Item__c =: molircds WITH SECURITY_ENFORCED Order By CreatedDate desc]; 
        
        Barcodeimageurl = 'https://www.webarcode.com/barcode/image.php?code='+morcd.Name+'&style=325&type=C128B&width=200&height=50&xres=1&font=3';
        
        //system.debug('Barcodeimageurl == '+Barcodeimageurl);
        
        
    }
    
    
    
}